# Generated by Django 2.2.5 on 2020-07-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('score', models.IntegerField(verbose_name='Puntaje')),
                ('repetitions', models.IntegerField(verbose_name='Repeticiones')),
                ('time', models.IntegerField(verbose_name='Tiempo')),
                ('level', models.IntegerField(verbose_name='Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('objective', models.CharField(max_length=128, verbose_name='Objetivo')),
                ('description', models.CharField(max_length=1024, verbose_name='Descripción')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient', verbose_name='Paciente')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapists.Therapist', verbose_name='Terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.IntegerField(verbose_name='Angulo')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.GameSession', verbose_name='Sesión de Juego')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Movement', verbose_name='Movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Minigame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(max_length=1024, verbose_name='Descripción')),
                ('movements', models.ManyToManyField(to='start.Movement', verbose_name='Movimientos')),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='minigame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.Minigame', verbose_name='Minijuego'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='movements',
            field=models.ManyToManyField(through='start.Performance', to='start.Movement'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start.TherapySession', verbose_name='Terapeuta'),
        ),
    ]
